Program.cs(21,37): error CS1061: 'Catalog' does not contain a definition for 'FindItem' and no accessible extension method 'FindItem' accepting a first argument of type 'Catalog' could be found (are you missing a using directive or an assembly reference?)